highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Leah Kumle
name: Leah Kumle
email: leahkumle@gmail.com
email_full: mailto:leahkumle@gmail.com
website: github.io/sustain
website_full: https://lkumle.github.io/sustain
address:
  city: Frankfurt
  country: Germany
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]

